let comparison1 = "Котик" > "котик" ? "Котик больше котик" : "Котик меньше котик";
console.log(comparison1);
let comparison2 = "Котик" > "китик" ? "Котик больше китик" : "Котик меньше китик";
console.log(comparison2);
let comparison3 = "Кот" > "Котик" ? "Кот больше Котик" : "Кот меньше Котик";
console.log(comparison3);
let comparison4 = "Привет" > "Пока" ? "Привет больше Пока" : "Привет меньше Пока";
console.log(comparison4);
let comparison5 = 73 > "53" ? "73 больше 53" : "73 меньше 53";
console.log(comparison5);
let comparison6 = false > 0 ? "false больше 0" : "false меньше или равно 0";
console.log(comparison6);
let comparison7 = 54 > true ? "54 больше true" : "54 меньше true";
console.log(comparison7);
let comparison8 = 123 > false ? "123 больше false" : "123 меньше false";
console.log(comparison8);
let comparison9 = true > "3" ? "true больше 3" : "true меньше 3";
console.log(comparison9);
let comparison10 = 3 > "5мм" ? "3 больше 5мм" : "3 меньше 5мм или не может быть сравнено";
console.log(comparison10);
let comparison11 = 8 > "-2" ? "8 больше -2" : "8 меньше -2";
console.log(comparison11);
let comparison12 = 34 > "34" ? "34 больше 34" : "34 меньше 34";
console.log(comparison12);
let comparison13 = null > undefined ? "null больше undefined" : "null меньше undefined";
console.log(comparison13);
